### ISSUE TITLE
Help online

### ISSUE THREAD

**Issue by cameyo42** [TobiahZ/processing-vscode#1]
Thank you for this extension.  
I'd like to open the processing reference from VSCode for the selected text (Shift-Ctrl-F in the IDE processing).  
Happy New Year.  
  
Best regards,  
Max  
  
p.s. debug processing code within VSCode is a dream :-)

**Comment by cameyo42** [comment]
Attached is my incomplete solution (tasks.json file)
[tasks.json.txt](https://github.com/TobiahZ/processing-vscode/files/692180/tasks.json.txt)
.
i don't know how to pass the selected text as argument.

Regards,
Max

**Comment by AvinZarlez** [comment]
Great feature suggestion! The code would need to be part of the extension.ts file, but it's doable.

I've already done a similar feature in my Unity Tools Extension project  https://github.com/TobiahZ/unity-tools

If you want (and know Node.JS), you could take a stab and implement a solution based off the way I do it in my Unity-Tools project.

Otherwise, I can do it but it may take me some time before I have an opportunity to sit down and work on it due to other work I need to do.

**Comment by cameyo42** [comment]
Sorry, i don't know Node.js.
Take your time...i'll wait :-)

Best regards,

Massimo

2017-01-11 0:33 GMT+01:00 Tobiah Zarlez <notifications@github.com>:

**Comment by AvinZarlez** [comment]
Took me a while, but this is now part of the latest version (1.1.0)!

Let me know if you have any issues @cameyo42

**Comment by cameyo42** [comment]
Hi Tobiah,
thanks for this extension !!!
I have a question:
after selecting a processing keyword (es. mouseX) and press Ctrl-Shift-P:
Selecting "Processing: Open Extension Documentation"      --> open
https://processing.org/reference/ web site
Selecting "Processing: Open Documentation for Selection"  --> open
https://www.google.com/search?as_sitesearch=processing.org&as_q=println web
site
Selecting "Processing: Search Processing Website"             --> open
https://processing.org/reference/ web site

Is there a way to open the help web page of selected word?
What i have missing ?

Best regards

Massimo

2018-05-09 21:02 GMT+02:00 Tobiah Zarlez <notifications@github.com>:

**Comment by AvinZarlez** [comment]
By help we page, do you mean opening https://processing.org/reference/mouseX.html directly?

The only API I saw for processings site was the Google search. I don't have a way to know what you selected is a processing keyword or not so best I can do is search and ideally first result is that page.

Unless I misunderstand your question?

-Tobiah Zarlez

Sent from Outlook for Android

________________________________

**Comment by cameyo42** [comment]
You understood well :-)
Your solution is ok for me.
Thanks again.

Massimo

2018-05-10 16:16 GMT+02:00 Tobiah Zarlez <notifications@github.com>:
