### ISSUE TITLE
P5 implamentation

### ISSUE THREAD

**Issue by Crashnorun** [TobiahZ/processing-vscode#10]
Hi TobiaZ,
Thanks for listing out the steps to getting VS Code to work with Processing. Would you happen to have similar process for P5.js?
Thanks

**Comment by AvinZarlez** [comment]
I haven't used P5.js, but it probably wouldn't be hard. I imagine a similar process between this and standard JS (natively supported in VSCode)?

**Comment by Crashnorun** [comment]
I just found a source to make it work for P5.js here: https://github.com/processing/p5.js/issues/1339

**Comment by AvinZarlez** [comment]
Great!
