### ISSUE TITLE
Add 'logging works' to readme

### ISSUE THREAD

**Issue by polyclick** [TobiahZ/processing-vscode#12]
I got interested in this extension but couldn't immediately find wether normal logging (print, println) would work in the vscode environment. I had to install and configure first to find it out.

Would be great if you just add some info that logging in supported to the readme.

_I think this is useful for people, like me, that do most of their debugging by printing things to the console. Especially in an environment like processing, where everything loops 60 times per second and you don't want to step through your code 1-by-1._

**Comment by AvinZarlez** [comment]
I don't know if I'd call "Logging" a feature of this extension. VSCode supports that via it's task file/integrated to command line features, this extension just makes using that a bit easier.

What suggested wording / language would you like to see added to the Readme? Feel free to make a quick PR (can even edit from within GitHub)

**Comment by mcanyucel** [comment]
> I got interested in this extension but couldn't immediately find wether normal logging (print, println) would work in the vscode environment. I had to install and configure first to find it out.
> 
> Would be great if you just add some info that logging in supported to the readme.
> 
> _I think this is useful for people, like me, that do most of their debugging by printing things to the console. Especially in an environment like processing, where everything loops 60 times per second and you don't want to step through your code 1-by-1._

In my case the `println` lines are not printed to the console. May I ask how did you make them visible in the vscode terminal?

**Comment by AvinZarlez** [comment]
@mcanyucel It should be in the debug console not the main terminal

**Comment by mcanyucel** [comment]
@TobiahZ thank you. But when I open the debug console, it is blank and it says `Please start a debug session to evaluate expressions`. Do I start the app differently than `Processing: Run Processing Project` ?

**Comment by AvinZarlez** [comment]
Sorry I think I meant to say output. https://code.visualstudio.com/Docs/editor/tasks#_output-behavior

**Comment by mcanyucel** [comment]
Thanks, I have updated the `tasks.json` as follows, but still the `println` lines are not displayed:

```
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": true,
        "panel": "dedicated",
        "showReuseMessage": true,
        "clear": true
      },
```

The part of my code that should be printing lines:
```
void setup() {
  // drop frame rate; 100k+ points causes high CPU load
  frameRate(15);
  // TODO canvas size cannot be variable; update this based on width & height variables
  size(1024, 768, P3D);
  background(0);
  coordinates = new ArrayList<PVector>();
  scaledCoordinates = new ArrayList<PVector>();
  ortho();
  cam = new PeasyCam(this, 800);
  cam.setMinimumDistance(5);
  cam.setMaximumDistance(1500);
  readFile();
  scaleCoordinates();
  println("Max is " + max + ", scale is " + scale);
  println("Xmin is " + xmin + ", Xmax is "  + xmax);
  println("Ymin is " + ymin + ", Ymax is "  + ymax);
  println("Zmin is " + zmin + ", Zmax is "  + zmax);
}
```
