### ISSUE TITLE
Building?

### ISSUE THREAD

**Issue by ghost** [TobiahZ/processing-vscode#13]
I couldnt find a build option and dont think its available. Could you try to implement that?

**Comment by AvinZarlez** [comment]
What is the issue you are having? This extension adds a build task (https://github.com/TobiahZ/processing-vscode#command-create-task-file ), but you have to configure your path. Have you followed the readme?

**Comment by ghost** [comment]
Sry i mean Exporting so i can send it as an exe

**Comment by AvinZarlez** [comment]
It should create an .exe in the output folder. Is there an extra export setting you want passed? If so, there isn't a default option but you can customize your task file with whatever setting you want as long as you are passing a command line parameter

**Comment by ghost** [comment]
I just reinstalled my windows and reinstalled visual studio code with the
processing language extension and i still cant see the .exe generated
anywhere. Do i have to set it up or something like that?


2018-02-20 21:26 GMT+01:00 Tobiah Zarlez <notifications@github.com>:

**Comment by AvinZarlez** [comment]
Are you saying the task file/build trigger doesn't work? Or trying to get the files after you build? Did you follow the instruction in the readme (Ex. Is Processing installed to your path?)

**Comment by ghost** [comment]
Yes I did. Everything works, so if I want to run the sketch it runs like
normal. But if I want to let's say send it to my friend, I don't have a
file that he could execute like an exe.

**Comment by AvinZarlez** [comment]
The task file outputs to a build folder. By default it's "out" in the workplace root. If the problem is you aren't exporting you just need to add the --export command (See this link for different parameters http://www.dsfcode.com/using-processing-via-the-command-line/ )

**Comment by ghost** [comment]
Well... I feel stupid now 😂 but thanks for your help

**Comment by AvinZarlez** [comment]
Don't feel stupid! It's good feedback you didn't know. Feel free to maybe write some instructions about putting in additional parameters into the task files, and then maybe contribute a PR to the readme to help others in the future!
