### ISSUE TITLE
"The following workspace folders are ignored since they use task version 0.1.0: TentacleWall"

### ISSUE THREAD

**Issue by Steve-VE** [TobiahZ/processing-vscode#16]
Hello, I have a problem...

I tried to follow the tutorial to "compile" and run my sketch with VSCode, but when I press Ctrl+Shift+B to run the task, it say "The following workspace folders are ignored since they use task version 0.1.0: TentacleWall"
(TentacleWall is the name of my project)

I don't know why to do and I don't have any clue... Somebody can help me ? 
Thank you :)

**Comment by austince** [comment]
Hey @Steve-VE! Which version of VSCode are you running?

**Comment by austince** [comment]
If you're using a Multi-root workspace, this should be fixed when we upgrade the tasks version (#15)  to 2.0.0, which is required by vscode.

**Comment by AvinZarlez** [comment]
#15  has been merged, let me know if this issue has been resolved

**Comment by andersugland** [comment]
> #15 has been merged, let me know if this issue has been resolved

Hey! I'm having the same issue. Using vscode version 1.21.1

It could very well be something with my setup as I have no clue. Although I followed the steps.

**Comment by AvinZarlez** [comment]
Between #15  and #22  this should be a solved issue.

@kamphare can you try remaking your task file and trying again?

**Comment by Steve-VE** [comment]
Hello, with this one, my problem is solved : 
``` JSON
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "run",
            "command": "processing-java",
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "args": [
                "--force",
                "--sketch=${fileDirname}",
                "--run"
            ]
        },
        {
            "taskName": "present",
            "command": "processing-java",
            "type": "shell",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "args": [
                "--force",
                "--sketch=${fileDirname}",
                "--present"
            ]
        }
    ]
}
```
Also, I'm using the last version of VSCode (1.23.1 today).
Sorry for the delay.
