### ISSUE TITLE
Space in file names

### ISSUE THREAD

**Issue by AvinZarlez** [TobiahZ/processing-vscode#3]
Issue brought up in #2 

Spaces in file names don't work.

Likely issue: File names should be in quotes and/or parsed for special characters like spaces

**Comment by austince** [comment]
I believe this is actually a Processing requirement and can be closed as a non-issue. When trying to make a file with spaces with the Processing IDE, this is the output:  
```
The sketch name had to be modified. Sketch names can only consist
of ASCII characters and numbers (but cannot start with a number).
They should also be less than 64 characters long.
```
Changed the name from `Test With Spaces` to `Test_With_Spaces`.

It could be good to add this as a note to the README. I'll make the change if you agree!

**Comment by AvinZarlez** [comment]
I already updated the documentation in https://github.com/TobiahZ/processing-vscode/commit/d271b35bae0287b08e9378b07c0d191ab15cbaff , but I did not realize that it was a Processing requirement! Makes sense to just close this issue.
