### ISSUE TITLE
processing pach should be defined as global user setting

### ISSUE THREAD

**Issue by aster94** [TobiahZ/processing-vscode#49]
hello,

i think that the processing-java path should be choose once.
this is also how vscode-arduino https://github.com/Microsoft/vscode-arduino did it. Since processing is aimed at a similar user audience a similar configuration would be quite user friendly

**Comment by AvinZarlez** [comment]
That's a fair point! As a user setting, it could be defined locally or globally depending on the user's desires, which makes it much better than being defined in the task file.

I will work on this later, shouldn't be too hard.

**Comment by aster94** [comment]
great, thak you :v:

**Comment by AvinZarlez** [comment]
Added in #50  / version 1.2.2

Let me know if you have any questions / experience any errors / have other suggestions!

**Comment by AvinZarlez** [comment]
I should note that you'll obviously have to update your task file for this to work, so it properly references the setting rather than the hardcoded string.

**Comment by aster94** [comment]
tested only now 😅 it works great! 🎉

**Comment by aster94** [comment]
also I think that the use of more global option would simplify the use of this package, for example an option to choose to create the `out` folder could be added. Now the same could be done by removing the `"--output=${workspaceRoot}\\out",` line from the task.json
