### ISSUE TITLE
document formatter 

### ISSUE THREAD

**Issue by ddownn** [TobiahZ/processing-vscode#53]
I can't find a way to format the .pde files in VS Code... I get a message "There is no document formatter for 'pde'-files installed."

Is there a formatter available?

**Comment by AvinZarlez** [comment]
This just came up with #52 

A code formattor is well out of the scope of this extension, and is clearly stated as such in the readme. I don't think making a processing specific formatter would make sense either. Not compared to extending support of an extension java formatter to also work in .pde files...

**Comment by ddownn** [comment]
Still, I’ve found the extension works really well and I appreciate being able to use it.
