### ISSUE TITLE
Visual Studio Code can't find processing-vscode extension

### ISSUE THREAD

**Issue by Samuil9999** [TobiahZ/processing-vscode#54]
I follow the instructions. But I get the "No extensions found." message.
![image](https://user-images.githubusercontent.com/661741/45034620-af591500-b060-11e8-9827-899d4b4c91c0.png)
![image](https://user-images.githubusercontent.com/661741/45034874-50e06680-b061-11e8-9d12-ac97ed2c7a5a.png)

Visual Studio Code version - 1.26.1
Operating System - Windows 7x32 

Does this mean that there is no x32 version of processing-vscode plugin?

**Comment by AvinZarlez** [comment]
I'm not familiar with the Win7x32 version of VSCode, but it should be similar / I don't see a reason why x32 should matter if its the same as the Win10/Mac/etc version?

What happens when you try to install from web? https://marketplace.visualstudio.com/items?itemName=Tobiah.language-pde

**Comment by Samuil9999** [comment]
You're right. It seems that the problem was due to the fact that the [https://marketplace.visualstudio.com](https://marketplace.visualstudio.com) website was unresponsive.

By the way, thank you for the great addon.
