### ISSUE TITLE
Strings inside 'println()' highlighted not as expected in some cases

### ISSUE THREAD

**Issue by ivanshuba** [TobiahZ/processing-vscode#57]
### Strings inside `println()` method highlighted not as expected in some cases
The issue appears for both `println()` and `System.out.println()` methods.

**To Reproduce the issue**
Create a simple *.pde file with the following content:
```java
void setup() {
  size(400, 400);
  println("This is a correct syntax highlight");
  if (10 = 10) { 
    println("This is a correct syntax highlight");
  }
  println("This is a INCORRECT syntax highlight");
}
```

then, to see even more different coloring behavior, change the content to the following
```java
println("This is a INCORRECT syntax highlight");
if (10 = 10) { 
  println("This is a correct syntax highlight");
}
println("This is a INCORRECT syntax highlight");
```

**Expected behavior**
Words are highlighted with varied colors which are different from the plain color used for highlighting the strings in other places. In my case, some words are purple and red instead of plain green.

**Possible reason**
It seems that the behavior depends on the number of curly braces placed above the mentioned text.

**Screenshots**
![image](https://user-images.githubusercontent.com/24988714/50662487-456d5f80-0faf-11e9-8547-d28020371d19.png)
![image](https://user-images.githubusercontent.com/24988714/50662479-3dadbb00-0faf-11e9-81cc-2c203dae4bdf.png)
![image](https://user-images.githubusercontent.com/24988714/50662514-5b7b2000-0faf-11e9-934d-83237eefe537.png)

**Desktop:**
 - OS: [Windows 7 x64, Service Pack 1]
 - VSCode: [1.30.1]
 - Processing: [3.4]

**Comment by AvinZarlez** [comment]
Interesting. I believe this is a problem with the pde.tmLanguage file.

Sadly, I didn't write that file. I borrowed it from the Processing Sublime plugin ( https://github.com/b-g/processing-sublime ) which hasn't been updated in a while.

I honestly don't have the time to dig into the pde.tmLanguage file and figure out what is going wrong to cause this. But if somebody does and makes a PR, I'd love to fix this.

**Comment by atnbueno** [comment]
The `10 = 10` is wrong ("_The left-hand side of an assignment must be a variable_"). The highlighting problem dissapears if you fix it: `10 == 10`
