### ISSUE TITLE
Processing Extension replace default java. Where Processing Debugger?

### ISSUE THREAD

**Issue by SupinePandora43** [TobiahZ/processing-vscode#58]
- OS: Windows 7 x32
 - Browser chrome
 - Version vscode - 1.30.1, processing extension - 1.2.2

i update java extensions(official pack), and now debugging with Processing Extension for java debug not work!!!
why extension add .pde how java file? and rename java language to Processing?!?!?!?!?why?!
and where Processing Debugger?!

**Comment by AvinZarlez** [comment]
This extension is not a debugger. I'm not sure your problem?

You have a different debugger that doesn't work because of this language extension? Is this problem when you are debugging .pde files or java files? I need you to explain your problem a bit better.

**Comment by SupinePandora43** [comment]
i can't normally debug java code, while Processing extension is enabled! with enabled Processing extension debug breakpoints in java, not placed!

**Comment by AvinZarlez** [comment]
I think I understand this bug and why it is. I'll try and fix it as soon as I can. I think it'll be an easy fix so it shouldn't take me too long.

**Comment by AvinZarlez** [comment]
I should have fixed this in v1.2.4 / #60 

Let me know if you still have any issues or the fix worked.
