### ISSUE TITLE
Cannot find the good file to run Processing

### ISSUE THREAD

**Issue by knupel** [TobiahZ/processing-vscode#59]
Hello,
I try to run my sketch Processing, but when I try to create a task, I don't have any task good to run Processing. I try all the four, but in no one I can see the line ""showOutput": "never"," Where I can find the good 'task.json' file. For information my code work perfectly on Sublime Text.

version :  Processing 3.4 OS Mojave / MacBook Pro 2018
<img width="705" alt="capture d ecran 2019-01-10 a 15 27 25" src="https://user-images.githubusercontent.com/3332269/50974943-aa174580-14ec-11e9-88fa-5c1ac838a2aa.png">

**Comment by AvinZarlez** [comment]
This extension adds a command to VSCode: "Processing: Create Task File" - It does not add it to the task template list (I don't believe an extension can add anything to that template list, that just comes up if you do not have a task file in your project)

You simply need to run that command, and it will automatically generate a task file for you that should run just fine. Just make sure you also follow the requirements: https://github.com/TobiahZ/processing-vscode#requirements
