### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jaydangar** [TobiahZ/processing-vscode#72]
I am getting compilation error 127, i am using mac and i have modified json file to work with macOS by changing windows to osx, but it did not help. can you provide json file for mac?

**Comment by AvinZarlez** [comment]
Can you be a bit more specific? When are you receiving this error? In what context/window?

By the json file I assume you mean the task file. The one generated should work for all platforms. The "windows" part overrides the context of the arguments that should work on Mac/Linux. But those lines point to where the file should be. If Processing is loading correctly and giving the error, the extension might be working correctly but your Processing/your app has the error.

Or is VSCode giving you this error somewhere?

**Comment by AvinZarlez** [comment]
Or perhaps, your bash is the one giving you that error? After a quick google search error 127 is for non-existing-command.

Did you follow the readme's instructions for set up?

Open Processing, and click the Tools -> Install "processing-java" menu item.

**Comment by AvinZarlez** [comment]
I'm going to close this issue just to keep things clean, assuming the above fixes your issue.

If not, please respond and reopen!
