### ISSUE TITLE
[Question] How to use multiple files like tabs in processing

### ISSUE THREAD

**Issue by CappedCola** [TobiahZ/processing-vscode#86]
Quick question is there any way i can have multiple files with classes because in Processing i just make a new tab and then i just have to make the object but in vscode i cant do that. Any solutions.

**Comment by AvinZarlez** [comment]
I'm not sure I understand the question?

You can have as many tabs as you'd like in VS code, and make new files at any point? https://code.visualstudio.com/docs/getstarted/userinterface#_tabs
