### ISSUE TITLE
can't install extension

### ISSUE THREAD

**Issue by nakednous** [TobiahZ/processing-vscode#88]
I followed the instructions to install the extension, but can't find it.

**Comment by tsopanid** [comment]
Same for me (using VSCodium)

**Comment by tsopanid** [comment]
Workaround:
- download .vsix file from https://marketplace.visualstudio.com/items?itemName=Tobiah.language-pde#overview
- drag to extensions in VS-Code/Codium

**Comment by AvinZarlez** [comment]
I have doublechecked and confirmed, it is definitely available from the VSCode marketplace.

I'm not sure if VSCodium has issues connecting to the VSCode marketplace, and I'm also not sure if @nakednous if you are also using VSCodium or normal VSCode.

Either way, you can definitely manually install like @tsopanid explained above, but not sure if there is anything I can do about it as the extension developer. That link itself should prove that the extension should be available on the marketplace.

Closing issue. Feel free to reopen if there is something im missing.

**Comment by nakednous** [comment]
@TobiahZ yes I'm using VSCodium as well on archlinux.

**Comment by AvinZarlez** [comment]
Confirmed https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

VSCodium does not use the main VS Code extension marketplace. I'd need to submit to their custom one. Probably doable? But honestly, not something I am likely to prioritize. I haven't had much time to work on this extension in general, let alone maintain two marketplaces
