### ISSUE TITLE
[BUG] No warning for invalid code

### ISSUE THREAD

**Issue by SonOfDiablo** [TobiahZ/processing-vscode#92]
**Describe the bug**
I was trying to run a small test sketch through Visual Studio Code and nothing happened.
After about half an hour of trying to add/re-add/change the Environment Path and the tasks.json, I finally decided to try and run the sketch in Processing and noticed a small typo `backgrounnd` instead of `background` and sure enough after fixing that typo everything started to work as expected!

**To Reproduce**
1. Make a typo
2. Run processing project

**Expected behavior**
Some kind of indication that the sketch contains an error would be great!
I'm not sure how much you are able to do, but something as simple as the red squiggles under something that is wrong would be a great improvement.

**VSCode (please complete the following information):**
 - Version: 1.52.1 (user setup)
 - Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
 - Date: 2020-12-16T16:34:46.910Z
 - Electron: 9.3.5
 - Chrome: 83.0.4103.122
 - Node.js: 12.14.1
 - V8: 8.3.110.13-electron.0
 - OS: Windows_NT x64 10.0.18363

**Comment by AvinZarlez** [comment]
Can you share the output logs when your run the task in VSCode?

Assuming you can run processing from your path (can test in a console, either in or out of VSCode) running from VSCode should output the error in those logs.

**Comment by SonOfDiablo** [comment]
It does indeed tell you in the terminal.
I must have missed that.

```
> Executing task: processing-java --force "--sketch=C:\Users\usr\Documents\scripts\Processing\TestSketch" "--output=C:\Users\usr\Documents\scripts\Processing\TestSketch\out" --run <

TestSketch.pde:39:0:39:0: The function backgrounnd(int) does not exist.
The terminal process "cmd.exe /d /c processing-java --force "--sketch=C:\Users\usr\Documents\scripts\Processing\TestSketch" "--output=C:\Users\usr\Documents\scripts\Processing\TestSketch\out" --run" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

Thank you for pointing this out :)
